name: if condition

on:
  push:
    branches:
      - "*"

jobs:
  only-on-dev:
    if: github.ref == 'refs/heads/main'
    name: Only on main branch
    runs-on: ubuntu-latest
    steps:
      - name: shell script
        run: echo "running  on main branch"

  