name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  call-build:
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit

  call-scan:
    needs: call-build
    uses: ./.github/workflows/image-scanner.yml
    secrets: inherit